---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможность перехода из корзины в список товаров
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Содержимое корзины сохраняется при перезапуске сессии браузера
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Страница магазина - SPA приложение, которое не перезагружает страницу
  - Вывод списка товаров должен быть постраничный 
  - Страница магазина должна иметь адаптивную верстку







